In [1]:
import pandas as pd
from pathlib import Path

In [2]:
# Load the data

In [3]:
data = Path("/Users/alexpayne/Scientific_Projects/mers-drug-discovery/sars2-retrospective-analysis/ligand_files_20250113")

In [4]:
tc = data / "tanimoto_combo_p_to_x/tanimoto_combo.csv"
mcs = data / "mcs_tanimoto_p_to_x/mcs_tanimoto.csv"
ecfp = data / "ecfp_tanimoto_p_to_x/fingerprint_similarities.csv"

In [5]:
tc_df = pd.read_csv(tc)
mcs_df = pd.read_csv(mcs)
ecfp_df = pd.read_csv(ecfp)

In [7]:
tc_flat = tc_df.melt(id_vars=["Reference_Ligand"], var_name="Query_Ligand", value_name="TanimotoCombo")

,Reference_Ligand,Query_Ligand,Type,Tanimoto,Tanimoto_Shape,Tanimoto_Color,Aligned
0,AAR-POS-d2a4d1df-39,EDG-MED-ee636701-1,TanimotoCombo,0.271808,0.400364,0.143253,True
1,AAR-POS-d2a4d1df-39,MAT-POS-fce787c2-3,TanimotoCombo,0.372194,0.522518,0.221871,True
2,AAR-POS-d2a4d1df-39,VLA-UCB-34f3ed0c-11,TanimotoCombo,0.371041,0.477539,0.264543,True
3,AAR-POS-d2a4d1df-39,BEN-BAS-c2bc0d80-7,TanimotoCombo,0.390772,0.490731,0.290814,True
4,AAR-POS-d2a4d1df-39,ALP-UNI-3735e77e-1,TanimotoCombo,0.343206,0.435922,0.250490,True
...,...,...,...,...,...,...,...
139951,LOR-NOR-30067bb9-7,TRY-UNI-2eddb1ff-7,TanimotoCombo,0.109498,0.218357,0.000639,False
139952,LOR-NOR-30067bb9-7,MAT-POS-a54ce14d-2,TanimotoCombo,0.121005,0.237902,0.004108,False
139953,LOR-NOR-30067bb9-7,ALP-POS-6f6ae286-3,TanimotoCombo,0.173757,0.330788,0.016725,False
139954,LOR-NOR-30067bb9-7,MAT-POS-a13804f0-4,TanimotoCombo,0.131769,0.261984,0.001555,False
139955,LOR-NOR-30067bb9-7,EDG-MED-10fcb19e-1,TanimotoCombo,0.152635,0.295159,0.010112,False

# combine 3 dataframes into a non-redundant dataframe

In [6]:
pd.merge(tc_df, mcs_df, on=["Reference_Ligand", "Query_Ligand"], how="outer")

,Reference_Ligand,Query_Ligand,Type,Tanimoto_x,Tanimoto_Shape,Tanimoto_Color,Aligned,MCS_Num_Atoms,Total_Num_Atoms,Tanimoto_y
0,AAR-POS-0daf6b7e-1,ADA-UCB-6c2cb422-1,TanimotoCombo,0.306946,0.459360,0.154532,True,16,66,0.242424
1,AAR-POS-0daf6b7e-1,ADA-UCB-6c2cb422-1,TanimotoCombo,0.000478,0.000956,0.000000,False,16,66,0.242424
2,AAR-POS-0daf6b7e-1,ALP-POS-133e7cd9-2,TanimotoCombo,0.255037,0.355660,0.154415,True,22,93,0.236559
3,AAR-POS-0daf6b7e-1,ALP-POS-133e7cd9-2,TanimotoCombo,0.003189,0.006377,0.000000,False,22,93,0.236559
4,AAR-POS-0daf6b7e-1,ALP-POS-1cbc2fae-1,TanimotoCombo,0.325542,0.407270,0.243814,True,16,75,0.213333
...,...,...,...,...,...,...,...,...,...,...
144311,WIL-MOD-03b86a88-6,VLA-UCB-50c39ae8-2,TanimotoCombo,0.407462,0.561639,0.253285,False,21,80,0.262500
144312,WIL-MOD-03b86a88-6,VLA-UCB-50c39ae8-7,TanimotoCombo,0.449383,0.603886,0.294880,True,22,85,0.258824
144313,WIL-MOD-03b86a88-6,VLA-UCB-50c39ae8-7,TanimotoCombo,0.403336,0.604563,0.202110,False,22,85,0.258824
144314,WIL-MOD-03b86a88-6,VLA-UNK-82501c2c-1,TanimotoCombo,0.591204,0.699508,0.482900,True,24,71,0.338028
144315,WIL-MOD-03b86a88-6,VLA-UNK-82501c2c-1,TanimotoCombo,0.526617,0.655806,0.397428,False,24,71,0.338028

# fix the column names to make a less tidy dataframe